language: node_js
node_js:
  - '6'
  - '8'
  - '10'
env:
  global:
    - secure: >-
        hkSsgWOM64NhsfLtlheIgPj3y0RGvfOG/BODjIjxsbGob7KAmg5jh8EH9Nv1yV9gYCEB+NdsJZBbt+MUOPjSsIGmUVoKI9rxh1xI3uCkPWOZXpeydeeFEPVyTNHQFfA2+7xnf5SBwFmTCExfBkNf9wU64HQxtEM9EdAxgRzQpjd0bzhrj7DVsX+nzD66/4DQ+wG7PT4+944bpg6kzR/qlqtz46WS3jcURwuqQnLz1tPMUVpv1I1NIGL1C9Qe0QsL+tHUo6ImnFP9J+OKwfq2eCxFibl159xNj2RObUoIMkxkDwobQU17xusIwM5pSfdreWBtqeXBQd3yyGDGN5feT9EY700OWFGhu2SSOt30uQAE3VjMocbJLM9TDJs9O9zaZq2AlSxJ5ky6cIDv4pWeIOMNXJ0NcpR57TWD8397ZiFQFBohsX/kA5V3YeY5eSFLNPYyY9xb83N6lx+TLt1AX3HWmhqMGHXTvmdno2DFtYIBSjS8RaqO8pLt9Qai07GYOelLL2uTgj4IVZTuZB/eMEn54/FjJtxtRnJ7SUwhkzD+blt4S9gtifctrEfVvw3cXmX+GKOwruEnQwAmeXhLQ5mV8JanSxxMUas7dduuyGwJ2ebOZ/XXSxlJfCppo0LhLZrKBncckx2fAJLp2qy75htIErIF/ZpzdNEitmmLp24=
